### ISSUE TITLE
Scope listing issue

### ISSUE THREAD

**Issue by mattbreeden** [piotrmurach/github#219]
https://github.com/peter-murach/github#33-scopes  

```ruby
g = Github.new(oauth_token: User.first.token)
g.scopes.list
=> NoMethodError: undefined method `list' for nil:NilClass
g.scopes
=> nil
```

**Comment by jmtame** [comment]
+1

**Comment by adrianpike** [comment]
:+1:

**Comment by jmtame** [comment]
@adrianpike if you're curious, i switched over to octokit, which is the official Github gem. it works great.

**Comment by Shwetakale** [comment]
@peter-murach I was debugging this issue. 

[In this method](https://github.com/peter-murach/github/blob/master/lib/github_api/api.rb#L161) we are defining public methods for all namespace which would be called on ``` Github.new``` object.

[Here](https://github.com/peter-murach/github/blob/master/lib/github_api/api.rb#L169) we have checked if that method is already defined

```
def self.method_added(method_name)
      method_name = method_name.to_s.gsub(/_with(out)?_callback_.*$/, '')
      # Only subclasses matter
      return if self.root?
      return if extra_methods.include?(method_name)
      # Only public methods are of interest
      return unless request_methods.include?(method_name)
      # Do not redefine
      return if (@__methods_added ||= []).include?(method_name) 
      ...
```

But in [Authorization module](https://github.com/peter-murach/github/blob/master/lib/github_api/authorization.rb#L6) we have attr_accessor for ```scopes``` which is considered as public method so above code snippet is not adding method.

Why this attr_accessor is added? I have also checked but I think that attr_accessor is not needed anywhere so we can remove that to fix this issue  or another solution is to change ```Scopes``` namespace.

Let me know your thoughts on this.
