### ISSUE TITLE
Check if a user is a public member of an organization API 

### ISSUE THREAD

**Issue by Shwetakale** [piotrmurach/github#240]
This API returns ```false``` if API is called by user who is not member of that organization. For eg.

     github.orgs.members.member? 'joshsoftware', 'anuja-joshi'

Returns ```false``` and 'anuja-joshi' is public member of that organization. I am getting her name in ``list``` api.

If I pass ```public: true``` option it works as expected but should work without that as well because according to [documentation](https://developer.github.com/v3/orgs/members/#check-membership) 

    GET /orgs/:org/members/:username

Checks if a user is, publicly or privately, a member of the organization.

**Comment by peter-murach** [comment]
Hi Shweta,

Thank you for using the library.

I imagine the api endpoint response has changed since this has been implemented as you have rightly pointed out. Do you have time to implement solution and submit? Could probably return response as is without coercing it into boolean type.

**Comment by Shwetakale** [comment]
@peter-murach Yes I would like to implement solution for this :)

**Comment by MaximAbramchuck** [comment]
@peter-murach I think that this issue can be closed, because solution is already in `master`.

**Comment by Shwetakale** [comment]
@MaximAbramchuck This should be open as response is http redirect which is not handled by this gem. Opened [PR](https://github.com/peter-murach/github/pull/258) for this let me know if you have any suggestions on that.

**Comment by piotrmurach** [comment]
Redirects will be handled as separate issue not specific to this api endpoint.
