### ISSUE TITLE
Does not follow redirects when repo has been moved/renamed?

### ISSUE THREAD

**Issue by andrewhavens** [piotrmurach/github#252]
I am noticing an issue in a project that I am working on. Some repos were recently moved to a different organization. So the response from fetching the repo is a redirect rather than the repo info.

``` ruby
repo_info = github.repos(user: user, repo: repo_name).get
p repo_info
#<Github::ResponseWrapper @body="#<Hashie::Mash documentation_url="https://developer.github.com/v3/#http-redirects" message="Moved Permanently" url="https://api.github.com/repositories/123?access_token=xyz">">
```

**Comment by jfabre** [comment]
That would be cool if this branch was merged. 
I'm currently using the fork in my code and it works well for me...
Is there any issue with it?

**Comment by peter-murach** [comment]
@jfabre please see my reasoning behind not merging the code [here](https://github.com/peter-murach/github/pull/258) I'm meaning to look into this but my time on open source is limited, I will see if I can spare some time coming weekend. Thanks for your patience.

**Comment by pg20** [comment]
Hi, Any updates or progress on this issue ? I am also facing same problem.

**Comment by peter-murach** [comment]
@pg20 Sorry quite busy atm, do you have time to look into it?

**Comment by codenamev** [comment]
For anyone considering tackling the port of that PR into middleware, see [octokit's implementation of redirects](https://github.com/octokit/octokit.rb/blob/master/lib/octokit/middleware/follow_redirects.rb) (they also use faraday so it should be fairly straightforward to port).

**Comment by jfabre** [comment]
Just stumbled on this issue again more than one year later! This is a sign, I'm tackling this today :)
