### ISSUE TITLE
Ruby 2.3: Implementations of #respond_to? need two parameters

### ISSUE THREAD

**Issue by olleolleolle** [piotrmurach/github#265]
Here is the implementation of `respond_to?`
https://github.com/peter-murach/github/blob/c7b4e08cf1f48d86ea071f545842246587d6a6e0/lib/github_api/response_wrapper.rb#L133

Here is how another project fixed it:

https://github.com/inukshuk/bibtex-ruby/commit/a65a370a8c7be93303c281477d1da65566cdad5f

**Comment by piotrmurach** [comment]
Hey Olle, I've released `v0.14.0` with the fix. Enjoy!
