### ISSUE TITLE
Does Not Return Status Of Merge

### ISSUE THREAD

**Issue by davidplappert** [piotrmurach/github#267]
Hey!

When I run a merge, I would like to get a return status of that merge. That way, I can test if there was any merge conflicts.

Thanks!

**Comment by piotrmurach** [comment]
Each response has `status` method to inspect the http response code. Have you tried that?

**Comment by v88NoahJerreel** [comment]
Hello @piotrmurach , is it possible to get the list of conflicted files without creating PR? 

Thank you!
