### ISSUE TITLE
2FA support

### ISSUE THREAD

**Issue by duckinator** [piotrmurach/github#268]
Supporting passing 2FA information when authenticating would be very useful. It is sent via the `X-GitHub-OTP` header.

https://developer.github.com/v3/auth/#working-with-two-factor-authentication

**Comment by duckinator** [comment]
Something like

```ruby
github = Github.new basic_auth: 'login:password', otp: 'blah'
```

**Comment by piotrmurach** [comment]
Thank you for using the library. Have you tried passing the info through headers [see](https://github.com/piotrmurach/github#35-two-factor) ? I like your suggestion of configuration option. Would you have time to take a stab at it? I'd really appreciate help to get this done.

**Comment by duckinator** [comment]
Ah, no, I didn't catch that part of the README! I'll look into sending a PR your way at some point in the next few days. :)

**Comment by piotrmurach** [comment]
Did you find time to look into this?

**Comment by duckinator** [comment]
Hey! I'd completely forgotten about this tbh. Thanks for the reminder.

I just started looking into this, but running `rake` results in the following error: https://gist.github.com/duckinator/33ebce738dc3d2993abcade7d00b1403

Commenting out the line calling that just yields a different error. Any idea what's up with that?

**Comment by Shwetakale** [comment]
@duckinator It looks like you are using latest version of ```rspec``` but in this gem rspec version is ```2.14.1```. 

Just doing bundle install will solve your problem as in development group 

     gem 'rspec',    '~> 2.14.1'

Locks the rspec version.

**Comment by duckinator** [comment]
Ah, looks like I needed to do `bundle exec rake` so it'd use the right version. Thanks @Shwetakale. :)

**Comment by Shwetakale** [comment]
:+1:

**Comment by duckinator** [comment]
Quick implementation that I think is right, but haven't verified or written tests for: https://github.com/duckinator/github/commit/b58a95a6e21ac0ee32681196686206e186ede727

That's all I can do tonight and I'm going to be busy for most of the next week; if someone wants to take over it in the meantime lmk in a comment here, otherwise I'll work on it next week.

**Comment by piotrmurach** [comment]
@Shwetakale thank you

@duckinator I can wait, having tests and verification would be nice.

**Comment by duckinator** [comment]
sorry about dropping the ball on this for... uh... over a year. looking at it again, I'm not really sure how to test it.

If someone has ideas for how to test it, lmk and I can try to finish it up and make a PR.

I also rebased my changes. https://github.com/duckinator/github/commit/5f84c5d506f99efdb9028d317640d56eaa5075db
