### ISSUE TITLE
there is no documentation

### ISSUE THREAD

**Issue by g2494** [piotrmurach/github#271]
http://www.rubydoc.info/github/piotrmurach/github/master/Github/Client/Repos

**Comment by Shwetakale** [comment]
@g2494 The link you are pointing to is valid and documentation exist on that link. Could you please elaborate more what you want to point out?

**Comment by piotrmurach** [comment]
@g2494 If you feel that there is anything missing beyond the GitHub API actual docs then please submit pull request and I will happily merge. I will close this issue as I cannot see any actions/docs to be done.
