### ISSUE TITLE
Multiple Error Messages in 422 Unprocessable Entity Response Are Not Properly Parsed

### ISSUE THREAD

**Issue by jonmchan** [piotrmurach/github#272]
When github returns HTTP ```422 - Unprocessable Entity``` error for a request such as in a failed PR creation, it contains very useful information on why the error occurred. Currently, github_api does not capture the error message. It would be useful to capture the error message within the exception.

**Comment by piotrmurach** [comment]
Thanks for reporting this, your suggestion makes perfect sense. 

Would you have time to look into it? A test showing the changed behaviour would be really useful.

**Comment by jonmchan** [comment]
Looks like the data model already supports this (https://github.com/piotrmurach/github/blob/master/lib/github_api/error/service_error.rb#L15), but the body variable isn't being populated.

**Comment by piotrmurach** [comment]
Would you have time to debug this?

**Comment by jonmchan** [comment]
I'll do as much as I can.... Further investigation shows that if I am missing including the head or base parameters in creating a pull request, the error is correct and the body is populated. 

When I create a PR off a branch that doesn't exist, the error message is swallowed and ```e.body = nil```. Apparently it is working for some things and not others. I will try to track down where the problem exists.

**Comment by piotrmurach** [comment]
That's really helpful, cheers! It seems like the body parsing may be at fault.

**Comment by jonmchan** [comment]
Here's the raw JSON body that is not being parsed correctly: 

```
"{\"message\":\"Validation Failed\",\"errors\":[{\"resource\":\"PullRequest\",\"code\":\"missing_field\",\"field\":\"head_sha\"},{\"resource\":\"PullRequest\",\"code\":\"missing_field\",\"field\":\"base_sha\"},{\"resource\":\"PullRequest\",\"code\":\"custom\",\"message\":\"No commits between master and noexist\"}],\"documentation_url\":\"https://developer.github.com/enterprise/2.6/v3/pulls/#create-a-pull-request\"}"
```

Still trying to track down why it isn't being parsed correctly.

**Comment by jonmchan** [comment]
Found the exact error.

In all the other error messages returned, errors include a hash with the key ```message```. In the PR create error, the message is in the 2nd error. There are 2 errors within this response.

**Comment by piotrmurach** [comment]
I would probably suggest saving this response in fixtures and writing some unit tests then we can trap the bug.

**Comment by jonmchan** [comment]
@piotrmurach here's your fixture. I have never used cucumber before so I don't know where to begin in writing the proper test. Hopefully you can use it to write the proper test. Also, I don't know how you want to handle the multiple error data type as the current model seems to only support holding 1 single error in the exception.

```json
{"http_interactions":[{"request":{"method":"post","uri":"https://<BASIC_AUTH>@api.github.com/repos/<USER>/github_api_test/pulls?access_token=<TOKEN>","body":{"encoding":"UTF-8","base64_string":"eyJ0aXRsZSI6IkZvdW5kIGEgYnVnIiwiYm9keSI6IkltIGhhdmluZyBhIHBy\nb2JsZW0iLCJiYXNlIjoibWFzdGVyIiwiaGVhZCI6ImRvZXNfbm90X2V4aXN0\nIn0=\n"},"headers":{"Accept":["application/vnd.github.v3+json,application/vnd.github.beta+json;q=0.5,application/json;q=0.1"],"Accept-Charset":["utf-8"],"User-Agent":["Github API Ruby Gem 0.14.2"],"Content-Type":["application/json"],"Authorization":["token <TOKEN>"],"Accept-Encoding":["gzip;q=1.0,deflate;q=0.6,identity;q=0.3"]}},"response":{"status":{"code":422,"message":"Unprocessable Entity"},"headers":{"Server":["GitHub.com"],"Date":["Fri, 01 Jul 2016 22:17:16 GMT"],"Content-Type":["application/json; charset=utf-8"],"Content-Length":["378"],"Status":["422 Unprocessable Entity"],"X-Oauth-Scopes":["repo"],"X-Accepted-Oauth-Scopes":[""],"X-Github-Media-Type":["github.v3; format=json"],"Access-Control-Expose-Headers":["ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval"],"Access-Control-Allow-Origin":["*"],"X-Github-Request-Id":["4a14594b-11ff-430e-94a0-5bdfc020b0ef"],"Content-Security-Policy":["default-src 'none'"],"Strict-Transport-Security":["max-age=31536000; includeSubdomains"],"X-Content-Type-Options":["nosniff"],"X-Frame-Options":["deny"],"X-Xss-Protection":["1; mode=block"]},"body":{"encoding":"UTF-8","base64_string":"eyJtZXNzYWdlIjoiVmFsaWRhdGlvbiBGYWlsZWQiLCJlcnJvcnMiOlt7InJl\nc291cmNlIjoiUHVsbFJlcXVlc3QiLCJjb2RlIjoibWlzc2luZ19maWVsZCIs\nImZpZWxkIjoiaGVhZF9zaGEifSx7InJlc291cmNlIjoiUHVsbFJlcXVlc3Qi\nLCJjb2RlIjoibWlzc2luZ19maWVsZCIsImZpZWxkIjoiYmFzZV9zaGEifSx7\nInJlc291cmNlIjoiUHVsbFJlcXVlc3QiLCJjb2RlIjoiY3VzdG9tIiwibWVz\nc2FnZSI6Ik5vIGNvbW1pdHMgYmV0d2VlbiBtYXN0ZXIgYW5kIGRvZXNfbm90\nX2V4aXN0In1dLCJkb2N1bWVudGF0aW9uX3VybCI6Imh0dHBzOi8vZGV2ZWxv\ncGVyLmdpdGh1Yi5jb20vZW50ZXJwcmlzZS8yLjYvdjMvcHVsbHMvI2NyZWF0\nZS1hLXB1bGwtcmVxdWVzdCJ9\n"},"http_version":null},"recorded_at":"Fri, 01 Jul 2016 22:17:15 GMT"}],"recorded_with":"VCR 2.9.3"}
```

**Comment by piotrmurach** [comment]
I was thinking more in terms of using the JSON body you've got back in unit test using rspec, something simple that instantiates the `ServiceError` instance and handles it. Would that be something you could do?

**Comment by jonmchan** [comment]
Here you go... a failing test to capture the behavior. 

https://github.com/jonmchan/github/blob/unprocessable_error_parsing_bugfix/spec/github/error/unprocessable_entity_spec.rb

**Comment by piotrmurach** [comment]
@jonmchan Thank you for all the debugging and test case, that was super useful and saved tons of time. I have implemented solution that will parse responses with multiple error messages. This is released as `v0.14.3` - enjoy!

**Comment by jonmchan** [comment]
Thanks @piotrmurach for the fix. It looks good. Would you mind if I submit a PR to expose the error hash? I'd like to customize the error message I return in my app based off of the message.

**Comment by piotrmurach** [comment]
Exposing errors directly sounds like a fine idea to me.
