### ISSUE TITLE
Cannot use global configuration user

### ISSUE THREAD

**Issue by khiem-nguyen** [piotrmurach/github#277]
I always have to pass user to list whenever make request even I set it in global configuration. Others config seems to be ok

**Comment by Shwetakale** [comment]
@khiem-nguyen Which API you are calling? I am checking repo list API and it seems to work fine.

In my global config, I have

    Github.configure do |config|
       config.user = 'shwetakale'
     end

And I am calling repos list API its giving me expected result as follow.

    github.repos.list 

    => #<Github::ResponseWrapper @body="[#<Hashie::Mash archive_url="https://api.github.com/repos/Shwetakale/aasm/{archive_format}{/ref}" assignees_url="https://api.github.com/repos/Shwetakale/aasm/assignees{/user}"....
