### ISSUE TITLE
hi,is very useful! thinks

### ISSUE THREAD

**Issue by AiPacino** [piotrmurach/github#279]
the tools is very useful for me, i can use the proxy for connect ???

**Comment by prasadsurase** [comment]
@AiPacino Can you please specify more details about what you have tried and what are trying to achieve?

**Comment by piotrmurach** [comment]
Yes, every connection option that `faraday` supports you can pass directly using the `connection_options` attribute like so:

```ruby
github = Github.new do |c|
  c.connection_options = {proxy: 'http://localhost'}
end
```
