### ISSUE TITLE
Retrieve event details

### ISSUE THREAD

**Issue by prasadsurase** [piotrmurach/github#280]
I am retrieving the activities of the user as and storing the details of some filtered activities. 

```ruby
acts = user.gh_client.activity.events.performed(user.github_handle)
acts.first.class
 => Hashie::Mash 
acts.first.id
 => "4589898989"
```
I need to retrieve details of an already existing activity. I only have the activity's id for reference.

**Comment by Shwetakale** [comment]
@prasadsurase If you look at Github's API Documentation they don't provide API to get activities details by id. [Here](https://developer.github.com/v3/activity/events/) is the link for documentation.

But If you have details of event with type you can fetch data.

For ex. If event is of type "IssueEvent" In list API we get details such as ```user, repo, issue id``` with these details we can use following API endpoint to get details of that issue

    Github::Client::Issues.new.get(user: 'joshsoftware', repo: 'code-curiosity', number: '107')

Hope this helps.

**Comment by prasadsurase** [comment]
@Shwetakale An issue can have multiple events like opened, commented, closed etc. I need the details of a specific event. I have an event's id for reference.

**Comment by Shwetakale** [comment]
@prasadsurase So If I am understanding it correctly you only have event id not issue number or comment number. Github doesn't seem to have API to give you details from that id. You might need to fetch events again and take details from that :disappointed:.
