### ISSUE TITLE
undocumented API - support

### ISSUE THREAD

**Issue by PatWie** [piotrmurach/github#282]
There are some useful, but undocumented api urls, like
`https://api.github.com/user/:id`. Is there a trick to request these apis?

Also works for:
`https://api.github.com/repositories/:id`

**Comment by prasadsurase** [comment]
@PatWie you can retrieve an repository's details using its _id_ after [this](https://github.com/piotrmurach/github/pull/284) PR has merged.

**Comment by Shwetakale** [comment]
@PatWie I think if API is not documented on [Github](https://developer.github.com/v3) then it's not supported officially by Github so they might update it or remove it any time which could break functionality of the apps using it so developers should not use such API's. Thoughts?

**Comment by PatWie** [comment]
Well, if you want to robustly deal with repository, it is a much better idea to just store the repo-id rather than everything else. In addition, GitHub allows users to change their nicknames. This also would screw up any tight integration.

I currently extent this library using

```
module GithubRepoExtension
  def get_by_id(*args)
    arguments(args, required: [:id])
    get_request("/repositories/#{arguments.id}", arguments.params)
  end
end
```

But looking forward the merge.

**Comment by piotrmurach** [comment]
@Shwetakale I think the risk is the same as for any other documented method call. GitHub chops and changes stuff quite frequently so I don't see a problem merging this in.

@prasadsurase Thanks for working on this PR.

@PatWie Done.
