### ISSUE TITLE
Retrieve repository info using repo id instead of using username and reponame

### ISSUE THREAD

**Issue by prasadsurase** [piotrmurach/github#283]
Hi

I am using github_api(0.14.5) to retrieve some details of a github repository. The issue is that I can't fetch the updated info of the same repository because it has been transferred to some other user.

``` ruby
2.3.0 :005 > user.gh_client.class
 => Github::Client 
2.3.0 :006 > user.gh_client.repos.class
 => Github::Client::Repos
2.3.0 :007 > m = user.gh_client.repos.method :get
 => #<Method: Github::Client::Repos#get(get_with_callback_repos)> 
2.3.0 :008 > m.source_location
 => ["/Users/prasad/.rvm/gems/ruby-2.3.0/gems/github_api-0.14.5/lib/github_api/api.rb", 185]
2.3.0 :009 > info = user.gh_client.repos.get 'prasadsurase', 'code-curiosity'
=> #some info
2.3.0 :010 >  info.class
 => Github::ResponseWrapper
```

The [get](https://github.com/piotrmurach/github/blob/master/lib/github_api/client/repos.rb#L162) method only takes the **username** and the **reponame**. It uses **/repos/{username}/{reponame}** api to retrieve the data. We can retrieve the same data using **/repositories/{repo-id}**. I was wondering if there exists a way to retrieve an repo's info using only its id. You can use [/repos/prasadsurase/code-curiossity](https://api.github.com/repos/prasadsurase/code-curiosity) and [/repositories/67219068](https://api.github.com/repositories/67219068) for comparision. If there isn't, I can send out an PR for the same.

Thanks.

**Comment by Shwetakale** [comment]
@prasadsurase I was trying to find out this API's documentation [here](https://developer.github.com/v3/) but I didn't find one. Could you please also paste documentation url here?

**Comment by PatWie** [comment]
This is the same as in #282. It is undocumented. However, it is probably the most useful api-query.

**Comment by Shwetakale** [comment]
@PatWie Yes this is very useful API but I am wondering why GitHub has not documented or released it.

I think opening support ticket to GitHub and will be good idea and I experienced that their support team is very much active so they might solve our query. If they start supporting this officially then it would be helpful.

**Comment by prasadsurase** [comment]
@Shwetakale @PatWie It was some pure luck on stumbling the second way to retrieve repository details. We use [this](https://developer.github.com/v3/repos/#list-all-public-repositories) to list all public repos. I just added the repo id and gave it a try. Have contacted Github Support regarding the same.

**Comment by Shwetakale** [comment]
@prasadsurase  (Y) I hope github releases this API officially.

**Comment by prasadsurase** [comment]
As per Github, "Thanks for reaching out. Indeed that is undocumented, but that's intentional for now. We'll be documenting that endpoint in the future (actually, it's not just that endpoint, you can replace a name with the ID for most other endpoints), but I can't promise when it will happen. Still, you can rely on this behavior in your scripts and applications -- we don't have any plans on changing it."

**Comment by piotrmurach** [comment]
Merged.
