### ISSUE TITLE
require 'hashie' for autoload

### ISSUE THREAD

**Issue by betesh** [piotrmurach/github#285]
The latest release of hashie (3.4.5) added a new file, lib/hashie/array.rb, which is autoloaded if you `require "hashie"` (See [diff](https://github.com/intridea/hashie/compare/v3.4.4...v3.4.5))

However, github_api loads hashie [here](https://github.com/piotrmurach/github/blob/2632ae380f01f0827180369e23df4dadb24c6693/lib/github_api/response/mashify.rb#L7) using `dependency 'hashie/mash'`, which bypasses `hashie.rb`, and therefore autoload, resulting in this error (re-raised by faraday for an unhelpful backtrace):

```
RuntimeError:
  missing dependency for Github::Response::Mashify: uninitialized constant Hashie::Extensions::Array
# faraday-0.9.2/lib/faraday/middleware.rb:20:in `new'
# faraday-0.9.2/lib/faraday/rack_builder.rb:48:in `build'
# faraday-0.9.2/lib/faraday/rack_builder.rb:163:in `block in to_app'
# faraday-0.9.2/lib/faraday/rack_builder.rb:163:in `each'
# faraday-0.9.2/lib/faraday/rack_builder.rb:163:in `inject'
# faraday-0.9.2/lib/faraday/rack_builder.rb:163:in `to_app'
# faraday-0.9.2/lib/faraday/rack_builder.rb:152:in `app'
# faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
# faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
# faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
# github_api-0.14.5/lib/github_api/request.rb:69:in `call'
# github_api-0.14.5/lib/github_api/request/verbs.rb:20:in `get_request'
```

Adding `require "hashie"` to the top of `lib/github_api/response/mashify.rb` should fix this.

**Comment by piotrmurach** [comment]
Thanks ❤️

**Comment by betesh** [comment]
Thank you!
