### ISSUE TITLE
User issue creation activity not retrieved. 

### ISSUE THREAD

**Issue by prasadsurase** [piotrmurach/github#286]
I am using github_api(0.14.5). I am trying to retrieve a user's IssuesEvent and IssueCommentEvent related events.

```ruby
2.3.0 :003 > acts = user.gh_client.activity.events.performed('narutosanjiv', auto_pagination: true)
2.3.0 :004 > act.gh_id
 => "4276305448"
2.3.0 :005 > act.ref_url
 => "https://github.com/PerfectMemory/mongoid-multitenancy/issues/24" 
2.3.0 :006 > acts.count
 => 54 
2.3.0 :007 > acts.collect(&:id).include? id.gh_id
 => false
```
The act.ref_url points to an issue created by user but it isn't listed in the retrieved activities. What am I doing wrong.

**Comment by piotrmurach** [comment]
Actually I don't know. Your best bet is to experiment and read the official [docs](https://developer.github.com/v3/activity/events/). It seems there are new endpoints added which are not present in the client, so this is something I would welcome a PR for.

**Comment by prasadsurase** [comment]
As per [docs](https://developer.github.com/v3/activity/events/), events older than 90 days aren't listed and hence the issue. Please specify the endpoints that are missing. I would be happy to contribute.

**Comment by piotrmurach** [comment]
I wish I could tell you right off top of my head. Unfortunately, this is a tedious process of checking [github_api/client](https://github.com/piotrmurach/github/tree/master/lib/github_api/client) against the current docs. Unless, of course, you will find a better way. If you have time this would be a great help to figure out what's missing and adding it. On my side I promise to review swiftly.

On separate note, I had a disk failure recently and I'm still in a process of settings things up including all my dotfiles. Once this is done I will resume in my open source stuff in earnest.
