### ISSUE TITLE
Projects API and other preview APIs

### ISSUE THREAD

**Issue by brendonrapp** [piotrmurach/github#289]
In September, GitHub introduced the "Projects" Kanban-style board feature. This included [a preview API](https://developer.github.com/v3/projects/) for interacting with Projects boards programatically. I would like to see support for Projects and other preview APIs ([Reactions](https://developer.github.com/v3/reactions/) is another preview API available now).

Support would require implementing calls for these endpoints, as well as including the Accept header with the custom media type required for accessing preview APIs.

**Comment by piotrmurach** [comment]
Would you have time to work on including the missing apis? I'm happy to merge any PRs. It should be self explanatory how to add new apis by following hierarchy and current implementation of other api calls with tests.
