### ISSUE TITLE
How to get stargazers_count and forks_count for Gist

### ISSUE THREAD

**Issue by soykje** [piotrmurach/github#295]
Hi,

I'm actually fetching one user's Gists with `Github.client.gists.list(user: "username")`. I would like to get also the _forks_count_, and the _stargazers_count_, like I do for the repositories. But I can't find how to do this, in the gem documentation, or even in the API's... Are these missing feature, or am I missing something?

Thx in advance for your answer!

**Comment by piotrmurach** [comment]
Honest answer - I don't know. Please refer to [official docs](https://developer.github.com/v3/gists/)

**Comment by soykje** [comment]
Hi,

Ok I just contacted the Github support about the `stargazers_count`, as I just figured it out about the `forks_count`.
So, to get a gist's forks_count, use something like `Github.client.gists.forks(_gist.id_).count`... that's simple :)
Still waiting for Github answer about stargazers, I'll put their answer here as soon as I got it.

**Comment by soykje** [comment]
Hi,

I just receive a quick answer from Github, about their API. They confirmed me that the `stargazers_count` was actually not available for gists in the API... No way I guess, also, or maybe fetching the html_url to parse the html page... :confused: 
Btw, I forgot to thank you, @piotrmurach, for your quick answer, and also at the same time of course, for your great job on this gem. So thx a lot! :+1:
