### ISSUE TITLE
Lots of warnings when listing repos

### ISSUE THREAD

**Issue by samphilipd** [piotrmurach/github#298]
I'm trying to list a user's repo like this:

```ruby
Github.new.repos.list(user: @user)
```

I see a lot of warnings output:

```
W, [2017-03-16T15:06:56.028111 #36962]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#size defined in Hash. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
W, [2017-03-16T15:06:56.028721 #36962]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#size defined in Hash. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
W, [2017-03-16T15:06:56.029257 #36962]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#size defined in Hash. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
W, [2017-03-16T15:06:56.029819 #36962]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#size defined in Hash. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
W, [2017-03-16T15:06:56.030357 #36962]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#size defined in Hash. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
W, [2017-03-16T15:06:56.035659 #36962]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#size defined in Hash. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
W, [2017-03-16T15:06:56.035963 #36962]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#size defined in Hash. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
W, [2017-03-16T15:06:56.036229 #36962]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#size defined in Hash. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
W, [2017-03-16T15:06:56.036469 #36962]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#size defined in Hash. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
W, [2017-03-16T15:06:56.036724 #36962]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#size defined in Hash. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
...more of the same...
```

What is going on here? Is this a bug in the gem or am I misusing it?

**Comment by piotrmurach** [comment]
The responses returned from GitHub api are wrapped by external gem dependency called `hashie`. The warnings are there because `hashie` internal method called `size` is overwritten by `size` key returned inside the json response. I'm not sure what is the best way to handle these apart from actually removing `hashie` as dependency and returning just a regular hash. Any thoughts?

**Comment by samphilipd** [comment]
Any particular reason to use Hashie over a regular hash?

**Comment by piotrmurach** [comment]
Back in the day :) I really liked the fact that returned json response could be queried as regular method calls, for instance, 'repo.comment.key.key....' was very nice to my eyes. However, with a hindsight I feel that it caused me more problems than actual good.

**Comment by samphilipd** [comment]
Might have to remove Hashie entirely then 🙈

You know what, I have some free time next week. I can work on a PR if you like?

**Comment by piotrmurach** [comment]
I think this is the most sensible way to solve this issue. Go for it!

**Comment by jfabre** [comment]
Hello, I have the same issue and I already hacked a local version to make this work with my project.
Even though it's cleaner to just use the hash syntax and not depend on hashie, I'm scared it will break at lot of code that depends on your gem. 

There's also a way to just silence hashie specified in https://github.com/intridea/hashie/blob/master/UPGRADING.md#upgrading-to-352

```
class MyMash < Hashie::Mash
  disable_warnings
end
```
So what I would like to know is:

1-  @samphilipd  Are you still planning on a PR for this or can I do it?
2- @piotrmurach Which of the two solutions you prefer?

**Comment by samphilipd** [comment]
I think we can't remove the dependency on Hashie.

Because we expose the "hash key as method" paradigm outside the gem, it might break a _lot_ of client code to change this.

Unless the maintainer is comfortable releasing a major version that is not backwards compatible, probably the `disable_warnings` is the best approach.

**Comment by piotrmurach** [comment]
Let's go with the `disable_warnings` option. Please could you submit PR?

**Comment by jfabre** [comment]
@piotrmurach If you're ever interested in removing hashie completely, I have a branch that I could submit with passing tests. Let me know.

**Comment by piotrmurach** [comment]
@jfabre Thanks for the offering! Atm I have quite few open source projects that I desperately need to work on, as well as I want to release new libraries. Therefore I'm more in maintenance mode for this library.

If you ask me what's most urgent for this library, I would definitely appreciate updating/adding new apis. For example this issue https://github.com/piotrmurach/github/issues/289 is a good starting point. 

At glance I think these are the missing apis:

* [projects](https://developer.github.com/v3/projects/)
* [reactions](https://developer.github.com/v3/reactions/)
* [issues.timeline](https://developer.github.com/v3/issues/timeline/) 
* [migration](https://developer.github.com/v3/migration/)
* [orgs.outside_collaborators](https://developer.github.com/v3/orgs/outside_collaborators/)
* [orgs.blocking](https://developer.github.com/v3/orgs/blocking/)
* [pull_requests.review_requests](https://developer.github.com/v3/pulls/review_requests/)
* [users.gpg_keys](https://developer.github.com/v3/users/gpg_keys/)
* [users.blocking](https://developer.github.com/v3/users/blocking/)
* [repos.invitations](https://developer.github.com/v3/repos/invitations/)
* [repos.traffic](https://developer.github.com/v3/repos/traffic/)
* [repos.community](https://developer.github.com/v3/repos/community/)

As you can see the list is a bit long and keeping the library line with the most current apis is significant work. Are you up for a challenge? 😄  If you work on these you will find plenty examples of feature & unit tests to follow.

**Comment by Carlows** [comment]
I'm still seeing this warning, was this released yet?
