### ISSUE TITLE
Bug: Watchers_count is grabbing the stargazers_count by accident

### ISSUE THREAD

**Issue by zackshapiro** [piotrmurach/github#317]
I noticed in the `list_spec.rb` file

```
it "gets watcher information" do
      stargazers = subject.list user, repo
      expect(stargazers.first.login).to eq('octocat')
end
```

And in my code, if I do

```
repos = Github::Client::Repos.new
response = repos.list user: self.gh_user, per_page: 100

gh = response.select { |l| l.html_url == url }

repo = gh.first

repo.watchers_count == repo.stargazers_count # true for any repo
```

**Comment by piotrmurach** [comment]
I have no idea why this would be the case as the response is simply parsed through json. Would you mind investigating this and submitting fix if you find out why?

**Comment by prasadsurase** [comment]
This is a Github issue. Have filed an ticket with Github.

**Comment by prasadsurase** [comment]
As per response from Github, this is the expected value. 
<img width="739" alt="screen shot 2017-08-23 at 3 36 54 pm" src="https://user-images.githubusercontent.com/562052/29610801-fc2052b6-8818-11e7-9713-ed358e89241f.png">

**Comment by piotrmurach** [comment]
@prasadsurase Thank you for investigating!

**Comment by RRM1000** [comment]
I'm still confused. How do you get the actual watchers count? They say it's in the subscribers_count but there is no such field in the json?! And no number corresponding to the actual Watcher count value from GitHub!
