### ISSUE TITLE
Updating multiple files in a single commit

### ISSUE THREAD

**Issue by jffs** [piotrmurach/github#321]
Hi, I'm using this gem for a university project and I want to know if there is a way to updating many files and then commit it in a single commit. I just could update one file at once and commit it. 
I read some workaround that's creates a new local branch, updates one file at onces and then merges it into the master branch...

Is there a way to modified more than one file and generate one commit? If I need to make the workaround, how could I create a new branch?

Sorry if I make the question in the wrong place

**Comment by piotrmurach** [comment]
I would encourage you to ask such questions on stackoverflow or similar. Browsing [official GitHub API docs](https://developer.github.com/v3/) is another good source for finding solution.
