### ISSUE TITLE
Is it possible to update the mime_types dependency?

### ISSUE THREAD

**Issue by Bandes** [piotrmurach/github#324]
I am unable to update `github_api` past 0.13.0 due to its dependency on `mime_types < 3.0` - is there any chance that this restriction could be relaxed? I have several necessary gems (most notable is the `google-api-ruby-client`) that require more recent releases of `mime_types`

**Comment by piotrmurach** [comment]
Hi Charles,

I think this is a good time to upgrade the gem to minimum Ruby `v2.0` and hence bump the mime_types requirement. I should have some time to release tomorrow.

**Comment by piotrmurach** [comment]
Release `v0.18.0` without `mime-types` dependency. Enjoy!
