### ISSUE TITLE
Issue pulling pull requests

### ISSUE THREAD

**Issue by jedrekdomanski** [piotrmurach/github#332]
Hi there,

Calling 
```github.repos.list user: 'my_user'``` uses endpoint https://developer.github.com/v3/repos/#list-your-repositories which gives me all repositories including repositories I own, but also repositories I have access to as a collaborator or organization member, that's why calling
```
repo.pull_requests.list
```
on a repo I do not own throws 404 Not Found error.

For example:
```@repos = github.repos.all.map(&:name)
@repos.each do |repo| 
 github = Github.new user: 'user-name', repo: repo
 github.pull_requests.list
end
```
This will throw an error 404 Not Found if I am not the owner of any of repo found.
Is there any way to pull repositories I own in my organisation?

**Comment by piotrmurach** [comment]
Hey, thanks for using the library!

Maybe try using an appropriate authorization token? I think depending on the token, you should have access to some things and not the others. Sorry, cannot be much more help.

**Comment by jedrekdomanski** [comment]
Hey, thanks! I was already able to figure it out. Upon deeper investigation I figured out that I needed to create a personal token to access Github API.
