### ISSUE TITLE
Create issues and set timestamps to other than "now"?

### ISSUE THREAD

**Issue by chriso0710** [piotrmurach/github#335]
I would like to migrate a large number of Redmine tickets with journals (comments) to github issues. Without loosing important information.
As a Ruby developer I would like to use this repo for creating the github issues and comments.

What worries me is the missing ability of setting the created_at and updated_at timestamp fields.
Is there a chance to set the timestamps directly via the github REST API? 

Thanks
Christian

**Comment by piotrmurach** [comment]
The [official GitHub API v3 docs](https://developer.github.com/v3/) are your friend! You can always drop a line to GitHub to ask them to expand the api? This issue tracker is more for issues with actual Ruby gem.
