### ISSUE TITLE
Review Request API

### ISSUE THREAD

**Issue by unhappychoice** [piotrmurach/github#348]
There is review request API documented in https://developer.github.com/v3/pulls/review_requests/ .
But I cannot find the API in this gem.
If there's no implementation for that, maybe I can implement it.

So, I just want to know why there's no implementation of the API.

**Comment by piotrmurach** [comment]
Sorry Yujisan, my focus is currently on the `tty` family of gems(over 25) for creating terminal tools (see https://ttytoolkit.org/). I'm not able to actively maintain this gem and rely on contributors instead to submit PRs if they require any functionality/APIs.
