### ISSUE TITLE
Dependency resolution

### ISSUE THREAD

**Issue by codenamev** [piotrmurach/github#368]
When you find some time for this lovely gem, could you pretty please release a minor version bump?  I am stuck with compatibility issues for `faraday` (which is locked at `~>0.8` in the current `0.18.2` release).

Thank you!  If I can help at all in this process I would be happy to 😄

**Comment by piotrmurach** [comment]
Will release shortly.

**Comment by piotrmurach** [comment]
Released `v0.19.0`
